<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findWithNotifications($date)
    {
        $qb = $this->createQueryBuilder('a');
        $qb
            ->leftJoin('a.answers', 'ans')
            ->leftJoin('a.ratings', 'r')
            ->where('a.created < :date')
            ->orHaving('COUNT(ans) > 0')
            ->orHaving('COUNT(r) > 0')
            ->setParameter('date', $date)
            ->groupBy('a.author')
        ;
        
        return $qb->getQuery()->execute();
    }
}
