<?php

namespace AppBundle\Repository;

/**
 * ArticleAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
