<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findWithNotifications($hoursAgo)
    {
        $date = new \DateTime();
        $date->modify("-$hoursAgo hours");
        $qb = $this->createQueryBuilder('u');
        $qb
            ->select('u', 'a', 'ans', 'r')
            ->join('u.articles', 'a')
            ->leftJoin('a.answers', 'ans')
            ->leftJoin('a.ratings', 'r')
            ->orWhere(
                $qb->expr()->orX(
                    $qb
                        ->andWhere('ans.created > :date')
                        ->andHaving('ans.emailSent = false')
                ) 
            )
            ->orWhere(
                $qb->expr()->orX(
                    $qb
                        ->andWhere('r.created > :date')  
                        ->orHaving('ans.emailSent = false')
                )    
            )
            ->setParameter('date', $date)
            
            ->groupBy('u')
            ;
        
        return $qb->getQuery()->execute();
    }
}
