api:
    type: rest
    prefix: /api
    resource: "@AppBundle/Resources/config/api_routing.yml"
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
client_article:
    path: /create-article
    defaults: { _controller: AppBundle:Client:createArticle }