<?php

namespace AppBundle\Entity;

/**
 * ArticleRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRateRepository extends \Doctrine\ORM\EntityRepository
{
}
